include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-arkbridge
PKG_RELEASE:=1

PKG_LICENSE:=CC-BY-NC-4.0
PKG_MAINTAINER:=LucxXxifer

LUCI_TITLE:=LuCI panel for arkbridge
LUCI_DEPENDS:=+luci-base +arkbridge
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
